# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "developers", :force => true do |t|
    t.column "name", :string
  end

  create_table "items", :force => true do |t|
    t.column "title",       :string
    t.column "description", :string
    t.column "notes",       :string
    t.column "status",      :integer
    t.column "effort",      :integer
    t.column "priority",    :integer
    t.column "sprint_id",   :integer
  end

  create_table "sprints", :force => true do |t|
    t.column "number", :integer
    t.column "start",  :date
    t.column "end",    :date
  end

  create_table "tasks", :force => true do |t|
    t.column "title",        :string
    t.column "description",  :string
    t.column "status",       :integer
    t.column "effort",       :integer
    t.column "item_id",      :integer
    t.column "developer_id", :integer
  end

end
